export const data = {
  name: 'Oumar',
  title: 'Développeur Fullstack',
  subtitle: 'React & Node.js',
  bio: [
    "Je suis Oumar, développeur fullstack passionné par la création d'expériences web modernes et intelligentes. Mon expertise couvre l'ensemble de la stack, du front-end React jusqu'aux APIs Node.js robustes.",
    "Ce qui me distingue ? Ma passion pour l'intelligence artificielle. J'intègre des fonctionnalités IA dans mes projets — NLP, ML, LLMs — pour créer des applications qui vont au-delà du classique.",
    "Basé en France, je recherche des projets ambitieux où la technique rencontre l'innovation.",
  ],
  github: 'https://github.com/ligaliomar',
  email: 'ligaliomar64@gmail.com',
  linkedin: '',
  available: true,
  stats: [
    { num: '3+', label: "Ans d'expérience" },
    { num: '15+', label: 'Projets livrés' },
    { num: '∞', label: 'Passion IA' },
  ],
  skills: [
    { name: 'React', icon: '⚛️', level: 92 },
    { name: 'Node.js', icon: '🟢', level: 88 },
    { name: 'TypeScript', icon: '🔷', level: 80 },
    { name: 'Python', icon: '🐍', level: 75 },
    { name: 'IA / LLMs', icon: '🤖', level: 82 },
    { name: 'PostgreSQL', icon: '🗄️', level: 78 },
    { name: 'MongoDB', icon: '🍃', level: 74 },
    { name: 'Docker', icon: '🐳', level: 70 },
    { name: 'AWS / Cloud', icon: '☁️', level: 65 },
    { name: 'GraphQL', icon: '🔗', level: 68 },
    { name: 'Next.js', icon: '▲', level: 85 },
    { name: 'Redis', icon: '🔴', level: 60 },
  ],
  projects: [
    {
      title: 'AI Chat Assistant',
      desc: 'Chatbot intelligent intégrant GPT-4 avec mémoire conversationnelle et personnalisation avancée.',
      tags: ['React', 'Node.js', 'OpenAI'],
      emoji: '🤖',
      theme: 'orange',
      link: 'https://github.com/ligaliomar',
    },
    {
      title: 'Dashboard Analytics',
      desc: 'Tableau de bord temps réel avec visualisations dynamiques et alertes intelligentes.',
      tags: ['React', 'D3.js', 'PostgreSQL'],
      emoji: '📊',
      theme: 'teal',
      link: 'https://github.com/ligaliomar',
    },
    {
      title: 'E-commerce Fullstack',
      desc: 'Plateforme e-commerce complète avec recommandations IA et paiements Stripe intégrés.',
      tags: ['Next.js', 'Node.js', 'Stripe'],
      emoji: '🛒',
      theme: 'purple',
      link: 'https://github.com/ligaliomar',
    },
    {
      title: 'NLP Text Analyzer',
      desc: 'Outil d\'analyse sémantique de texte utilisant des modèles de langage pour extraction d\'entités.',
      tags: ['Python', 'FastAPI', 'React'],
      emoji: '🧠',
      theme: 'green',
      link: 'https://github.com/ligaliomar',
    },
  ],
  experiences: [
    {
      date: '2025 — Présent',
      role: 'Développeur Fullstack Senior',
      company: 'Freelance / Remote',
      desc: 'Conception et développement d\'applications web React/Node.js avec intégration IA. Accompagnement de startups dans la mise en place de leur stack technique.',
    },
    {
      date: '2022 — 2023',
      role: 'Développeur Fullstack',
      company: 'Agence Digital',
      desc: 'Développement d\'interfaces complexes, optimisation des performances et mise en place de tests automatisés. Migration de 3 projets vers React 18.',
    },
    {
      date: '2019 — 2021',
      role: 'Développeur Web Junior',
      company: 'Startup Tech',
      desc: 'Premiers pas en production : API REST Node.js, intégrations tiers, participation à des projets IA expérimentaux.',
    },
  ],
}
